# Generated by Django 4.1.2 on 2022-11-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subsribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subsribers',
            new_name='subscribers',
        ),
    ]
